# Generated by Django 3.2.7 on 2021-09-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmaComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AWBnumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PharmaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AWBnumber', models.CharField(max_length=100)),
                ('beaconId', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=20)),
            ],
        ),
    ]
